# Generated by Django 5.2.4 on 2025-10-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-is_default', 'id'), 'verbose_name_plural': 'Addresses'},
        ),
    ]
