version: '2.4'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  redis:
    image: redis:7

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn nexus.wsgi:application --bind 0.0.0.0:8000
    entrypoint: /app/entrypoint.sh
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

volumes:
  postgres_data: