# render.yaml

databases:
  - name: nexus-db
    plan: free

services:

  # 2. The Redis Cache Service
  - name: nexus-redis
    type: redis
    plan: free # Use the free plan
    ipAllowList: [] # Allow all internal

  # 3. The Django Web Service
  - name: nexus-web
    type: web
    plan: free # Use the free plan
    runtime: docker
    # This tells Render where your Dockerfile is. It's the project root.
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/products/ # A simple path to check if the app is alive
    envVars:
      # --- Environment Variables ---
      # Pulls the database connection string from the 'nexus-db' service we defined
      - key: DB_URL
        fromService:
          name: nexus-db
          property: connectionString
      # Pulls the Redis connection string from the 'nexus-redis' service
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString

      # --- Your application secrets ---
      # You will set these values in the Render dashboard for security
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: 0
      - key: ALLOWED_HOSTS
        # Render provides the domain, e.g., project-nexus.onrender.com
        value: .onrender.com

    buildCommand: "python manage.py migrate && python manage.py collectstatic --no-input"